{*
* 2018 Areama
*
* NOTICE OF LICENSE
*
* This source file is subject to the Academic Free License (AFL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/afl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@areama.net so we can send you a copy immediately.
*
*
*  @author Areama <contact@areama.net>
*  @copyright  2018 Areama
*  @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
*  International Registered Trademark & Property of Areama
*}
<script type="text/javascript">
    window.addEventListener('load', function(){
        arlsf.ajaxUrl = '{$ajaxUrl nofilter}'{* URL generated by Link object, no escape necessary. Escaping will break functionality *};
        arlsf.token = '{$token|escape:'htmlall':'UTF-8'}';
        arlsf.delayFirstMin = {$generalConfig->delay_first[0]|intval};
        arlsf.delayFirstMax = {$generalConfig->delay_first[1]|intval};
        arlsf.displayTime = {$generalConfig->delay|intval};
        arlsf.delayMin = {$generalConfig->delay_between[0]|intval};
        arlsf.delayMax = {$generalConfig->delay_between[1]|intval};
        arlsf.inAnimation = '{$generalConfig->animation|escape:'htmlall':'UTF-8'}';
        arlsf.outAnimation = '{$generalConfig->out_animation|escape:'htmlall':'UTF-8'}';
        arlsf.displayTimes = '{$generalConfig->display_times|intval}';
        arlsf.closeLifetime = {$generalConfig->close_lifetime|intval};
        arlsf.sessionKey = '{$sessionKey|escape:'htmlall':'UTF-8'}';
        {if (($ordersConfig->product) && $productId)}
            arlsf.orderCurrentProduct = {$productId|intval};
            arlsf.orderCurrentProductLimit = {$ordersConfig->product_times|intval};
        {/if}
        {if (($addToCartConfig->product || $visitorConfig->enabled) && $productId)}
            arlsf.cartCurrentProduct = {$productId|intval};
            arlsf.cartCurrentProductLimit = {$addToCartConfig->product_times|intval};
        {/if}
        {if isset($generalConfig->sound) and $generalConfig->sound}
            arlsf.sound = '{$path|escape:'htmlall':'UTF-8'}views/sound/{$generalConfig->sound|escape:'htmlall':'UTF-8'}';
            arlsf.soundTimes = {$generalConfig->sound_times|intval};
        {/if}
        {if isset($addToCartConfig->enabled) and $addToCartConfig->enabled and $last_cart}
            arlsf.lastCartItem = '{$last_cart|escape:'htmlall':'UTF-8'}';
        {/if}
        arlsf.init();
    });
</script>
<style type="text/css">
    body #arlsf-notification .arlsf-inner{
        {if $generalConfig->opacity}
            opacity: {$generalConfig->opacity|intval / 100};
        {/if}
        {if $generalConfig->background_color}
            background: {$generalConfig->background_color|escape:'htmlall':'UTF-8'};
        {/if}
        {if $generalConfig->d_height}
            height: {$generalConfig->d_height|intval}px;
        {/if}
        {if $generalConfig->d_width}
            width: {$generalConfig->d_width|escape:'htmlall':'UTF-8'};
        {/if}
    }
    body #arlsf-notification:hover .arlsf-inner{
        {if $generalConfig->hover_opacity}
            opacity: {$generalConfig->hover_opacity|intval / 100};
        {/if}
    }
    body #arlsf-notification .arlsf-image{
        {if $generalConfig->d_height}
            height: {$generalConfig->d_height|intval}px;
            width: {$generalConfig->d_height|intval}px;
        {/if}
    }
    body #arlsf-notification .arlsf-content p{
        margin-bottom: {$generalConfig->line_space|intval}px;
        {if $generalConfig->text_color}
            color: {$generalConfig->text_color|escape:'htmlall':'UTF-8'};
        {/if}
        {if $generalConfig->font_size}
            font-size: {$generalConfig->font_size|intval}px;
        {/if}
    }
    body #arlsf-notification .arlsf-content{
        {if $generalConfig->d_height}
            padding-left: {$generalConfig->d_height|intval + 8}px;
        {/if}
    }
    body #arlsf-notification{
        
        {if $generalConfig->border_color}
            border: 1px solid {$generalConfig->border_color|escape:'htmlall':'UTF-8'};
            height: 94px;
        {/if}
        {if $generalConfig->d_height}
            height: {$generalConfig->d_height|intval}px;
        {/if}
        {if $generalConfig->d_width}
            width: {$generalConfig->d_width|escape:'htmlall':'UTF-8'};
        {/if}
        {if $generalConfig->border_radius}
            border-radius: {$generalConfig->border_radius|intval}px;
        {/if}
        {if $generalConfig->shadow_color && $generalConfig->shadow_size}
            box-shadow: 0 0 {$generalConfig->shadow_size|intval}px {$generalConfig->shadow_color|escape:'htmlall':'UTF-8'};
        {/if}
        {if $generalConfig->text_color}
            color: {$generalConfig->text_color|escape:'htmlall':'UTF-8'};
        {/if}
        
        {if $generalConfig->position == 'top_left'}
            top: {$generalConfig->top|intval}px;
            bottom: auto;
            left: {$generalConfig->left|intval}px;
            right: auto;
        {elseif $generalConfig->position == 'top_right'}
            top: {$generalConfig->top|intval}px;
            bottom: auto;
            left: auto;
            right: {$generalConfig->right|intval}px;
        {elseif $generalConfig->position == 'bottom_left'}
            top: auto;
            bottom: {$generalConfig->bottom|intval}px;
            left: {$generalConfig->left|intval}px;
            right: auto;
        {elseif $generalConfig->position == 'bottom_right'}
            top: auto;
            bottom: {$generalConfig->bottom|intval}px;
            left: auto;
            right: {$generalConfig->right|intval}px;
        {/if}
        
        
    }
    body #arlsf-notification a{
        {if $generalConfig->link_color}
            color: {$generalConfig->link_color|escape:'htmlall':'UTF-8'};
        {/if}
    }
    
    body #arlsf-notification button{
        {if $generalConfig->close_btn_color}
            color: {$generalConfig->close_btn_color|escape:'htmlall':'UTF-8'};
        {/if}
    }
    body #arlsf-notification.active, #arlsf-notification.animated{
        {if $generalConfig->opacity}
            opacity: {$generalConfig->opacity|intval / 100};
        {/if}
    }
    {if $generalConfig->hover_opacity}
        body #arlsf-notification.active:hover, #arlsf-notification.animated:hover{
            opacity: {$generalConfig->hover_opacity|intval / 100};
        }
    {/if}
    @media (max-width: 478px){
        body #arlsf-notification{
            {if $generalConfig->m_position == 'top'}
                top: {$generalConfig->m_top|intval}px;
                bottom: auto;
                left: {$generalConfig->m_left|intval}px;
                right: {$generalConfig->m_right|intval}px;
            {elseif $generalConfig->m_position == 'bottom'}
                top: auto;
                bottom: {$generalConfig->m_bottom|intval}px;
                left: {$generalConfig->m_left|intval}px;
                right: {$generalConfig->m_right|intval}px;
            {/if}
            {if $generalConfig->m_height}
                height: {$generalConfig->m_height|intval}px;
            {/if}
            {if $generalConfig->m_width}
                width: {$generalConfig->m_width|escape:'htmlall':'UTF-8'};
            {/if}
        }
        body #arlsf-notification .arlsf-inner{
            {if $generalConfig->m_height}
                height: {$generalConfig->m_height|intval}px;
            {/if}
            {if $generalConfig->m_width}
                width: {$generalConfig->m_width|escape:'htmlall':'UTF-8'};
            {/if}
        }
        body #arlsf-notification .arlsf-image{
            {if $generalConfig->m_height}
                height: {$generalConfig->m_height|intval}px;
                width: {$generalConfig->m_height|intval}px;
            {/if}
        }
    }
    {$generalConfig->extra_css|escape:'htmlall':'UTF-8'}
</style>